Fixed /scim/v2/User/# endpoint to return 404 instead of 500
nerc-project/coldfront-plugin-api pull request #21
Opened 2023-12-20 20:09 UTC by QuanMPhm

Fixes https://github.com/nerc-project/coldfront-plugin-api/issues/15 by performing a try-except block around the query call.

The last PR was closed because while trying to reset and rebasing and squashing, I accidentally pushed such that the main branch and my local branch was identical, thus automatically closing the PR?

2023-12-20 20:12 UTC, knikolla requested changes
Additionally, please add a unit test.

2023-12-20 20:12 UTC, knikolla commented on src/coldfront_plugin_api/scim_v2/users.py
> +from django.http import Http404
This import is no longer used.

2023-12-20 21:49 UTC, QuanMPhm commented
@knikolla The test file has been added.

2023-12-20 22:45 UTC, knikolla commented
> @knikolla The test file has been added.

There is no need to create a new file. There already is afile and class for testing users.

2023-12-21 17:39 UTC, QuanMPhm commented
@knikolla I've added my test function into `test_users.py`

2023-12-21 17:54 UTC, knikolla requested changes

2023-12-21 17:54 UTC, knikolla commented on src/coldfront_plugin_api/tests/unit/test_users.py
> +        # Make a http request to scim endpoint
This comment is not necessary and quite far from the line of code that it applies to, please remove it.

2023-12-21 18:18 UTC, QuanMPhm commented
@knikolla Comment removed

2023-12-21 18:24 UTC, knikolla commented
> @knikolla Comment removed

I understand that it's easier to use the GitHub website to make quick commits, however please at least attempt to write a good commit message rather than just "Update test_users.py". See https://github.com/CCI-MOC/ops-docs/blob/master/policies/0007-pull-requests.md

2023-12-21 18:24 UTC, merged